language: php

git:
  submodules:
    false

services:
  - mysql
  - redis

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.2

before_install:
  - mysql -e 'CREATE DATABASE giantbomb_test;'
  - openssl aes-256-cbc -K $encrypted_5e7297588eb9_key -iv $encrypted_5e7297588eb9_iv -in .env.travis.enc -out .env -d

install:
  - composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
  - php artisan migrate:refresh && php artisan db:seed && php artisan db:seed --class CreateTestDataForTestsSeeder

script: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clove