language: php

git:
  submodules:
    false

services:
  - mysql
  - redis

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.2

before_install:
  - mysql -e 'CREATE DATABASE giantbomb_test;'
  - cp .env.travis .env

install:
  - composer install --prefer-dist --no-interaction --no-suggest
  - php artisan migrate:refresh && php artisan db:seed && php artisan db:seed --class CreateTestDataForTestsSeeder

script: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clove