language: php

git:
  submodules:
    false

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - php: 7.1

install:
  - composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clove