version: '3'
services:

  gb_nginx:
    container_name: gb_nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - gb_php
    restart: always

  gb_php:
    container_name: gb_php
    build:
      context: ./.docker/php
    volumes:
      - ./:/var/www/html
    links:
      - gb_db
      - gb_redis
    restart: always

  gb_redis:
    container_name: gb_redis
    image: redis
    volumes:
      - ./.docker/cache/redis:/data
    links:
      - gb_echo_server
    restart: always

  gb_db:
    container_name: gb_db
    image: postgres
    volumes:
      - ./.docker/cache/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
     - "5432:5432"
    restart: always

  gb_echo_server:
    container_name: gb_echo_server
    build:
      context: ./.docker/echo-server
    ports:
     - "6001:6001"
    restart: always

  gb_queue_worker:
    container_name: gb_queue_worker
    build:
      context: ./.docker/queue-worker
    volumes:
      - ./:/var/www/html
    links:
      - gb_db
      - gb_redis
    restart: always
