---
- hosts: giantbomb

  tasks:

  - name: Install Base Required Packages
    apt:
      name: "{{ item }}"
      state: installed
      update_cache: yes
    become: yes
    with_items:
      - apt-transport-https
      - lsb-release
      - ca-certificates
      - ant
      - unzip
      - zip

  - name: Add Repo for PHP7.1
    apt_repository:
      repo: ppa:ondrej/php
      state: present
    become: yes

  - name: Install Laravel Required Packages
    apt:
      name: "{{ item }}"
      state: installed
      update_cache: yes
    become: yes
    with_items:
      - php7.1
      - php7.1-xml
      - php7.1-mysql
      - php7.1-mbstring
      - php7.1-curl

  - name: Install Composer
    shell: curl -sS https://getcomposer.org/installer | php
    become: yes

  - name: Move into User Bin
    shell: mv composer.phar /usr/bin/composer
    become: yes